services:
  - type: web
    name: hatrick-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: GROQ_API_KEY
        sync: false
      - key: HUGGINGFACEHUB_API_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
